### ISSUE TITLE
Some Suggestions/Additions

### ISSUE THREAD

**Issue by zumwalt2001** [TMan9654/PyPDFCompare#1]
TMan9654
Came here from your post on reddit.
Thanks for this, I think it will really help.

My main use would be to compare pdf's to check for revisions, when the revisioning is general. ie, "Grade Changes".
It appears it will do the job.

Comments/Requests:
1. I see you have mentioned it only does 2 sheets at a time, and you might add multiple sheets in the future. That would be extremely useful.
2. Since you know pdf;s much better than I, is it possible to compare multi-sheet pdf's? 
3. An open file GUI would be nice with file names containing spaces to get the argv's correct.
 
My level of python is beginner at best, but I might able to do 2 & 3. However, your code would be better.

**Comment by TMan9654** [comment]
Hello zumwalt2001,

Happy to hear this tool would be useful for you. I appreciate the feedback!

Lets address some of your comments:
1. In your case, I'm not sure if you are referring to a "sheet" being a PDF file or a page within a PDF file. If you are referring to a page, PyPDFCompare already supports comparing as many pages as in the PDF file. For example, If I have 2 PDF files containing say 500+ pages, PyPDFCompare will iterate through and compare all 500+ pages. This however is only done sequentially at the moment. 

2. If you are wanting to compare more than 2 PDF files, adding this functionality would be trivial. The only downside here would be processing time. I suppose if the number of PDF's gets excessive, it would be hard to examine so perhaps just increasing the limit from 2 to maybe 3 or 4. I can play around with it and see if it makes any sense. As previously mentioned, multiple pages in a PDF is already supported.

3. Lastly, I can certainly add a GUI based version to the repo. Below is a fairly simple window I tossed together as an example of how it'd kinda look. Id add a button to start the compare and have the attached paths listed in the drop window to better see whats going on. Let me know what you think!
![Example GUI Window  ISSUE](https://github.com/TMan9654/PyPDFCompare/assets/118219045/04e288c3-13dd-4fd8-abe2-ba55b7028885)

**Comment by TMan9654** [comment]
I have created a GUI version and added it to the repo. If you have no further comments on this, I will mark this issue complete.

**Comment by zumwalt2001** [comment]
The GUI version is very helpful. I also like having the two options to play around with

**Comment by TMan9654** [comment]
Perfect! Feel free to post issues as you come up with any other suggestions!
